language: node_js
sudo: false
branches:
  only:
    - master
script:
  - "casperjs test test/test.js"
notifications:
  webhooks:
    on_start: always
    urls:
      - http://buildlight.collectiveidea.com/